[package]
name = "rust-embedded-intro"
version = "0.2.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7.4"
panic-halt = "0.2.0"

[dev-dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
rtt-target = "0.5.0"
